as if you're gonna say no
khayyamsaleem/hli114 pull request #4
Opened 2019-02-27 02:33 UTC by aschlumpf

2019-02-27 17:10 UTC, khayyamsaleem requested changes
think again

2019-02-27 17:10 UTC, khayyamsaleem commented on nibelungenlied/nibelungenlied.org
> +- Brunhild griefs, and when Gunther learns why he doesn't dare to question Siegfried
*grieves

2019-02-27 17:10 UTC, khayyamsaleem commented on nibelungenlied/nibelungenlied.org
> +* Siegfried's Rape of Bunhild
*Brunhild

2019-02-28 01:22 UTC, aschlumpf commented on nibelungenlied/nibelungenlied.org
> +* Siegfried's Rape of Bunhild
nay

2019-02-28 01:23 UTC, aschlumpf commented
i was speaking asymptotically

2019-02-28 02:23 UTC, khayyamsaleem reviewed
looks good

2019-02-28 02:24 UTC, khayyamsaleem approved these changes

2019-02-28 02:24 UTC, merged